spring:
  application:
    name: shopping-application

  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      indent-output: true

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 8640000

server:
  port: 8080
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: DEBUG

